name: Build Wheels

on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'

jobs:
  build_dist:
    name: Build Distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build sdist
        run: |
          pip install build
          python -m build --sdist --wheel

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*

  store_tag_artifacts:
    needs: [build_dist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/*
