name: Test

on:
  push:
  pull_request:

jobs:
  pre-commit:
    name: Pre-commit checks (Black, Flake8, MyPy, ...)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: pre-commit/action@v3.0.0

  test:
    name: Test on CPython ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.7"
          - python: "3.8"
          - python: "3.9"
          - python: "3.10"
          - python: "3.11"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install CPython ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"
          architecture: x64
      - name: Install Test dependencies
        run: |
          pip install -U --upgrade-strategy=eager --pre -e .[testing]
      - name: Run tests
        run: |
          pytest -v
      - name: Publish to coveralls.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install 'coveralls'
          coveralls --service=github
